In [9]:
import numpy as np


# Find Empty cases

def Find_blanks(grid, i, j):
        for x in range(i,4):                 # traverse grid lines
                for y in range(j,4):         # travers grid columns
                        if grid[x][y] == 0:
                                return x,y
        for x in range(0,4):
                for y in range(0,4):
                        if grid[x][y] == 0:
                                return x,y
        return -1,-1

    
# find the color e which consists of the three constraints

def RowColumn_Valid(grid, i, j, e):     
        ligne_valide = all([e != grid[i][x] for x in range(4)])           # row had different color (constraint 1)
        if ligne_valide:
                colonne_valid = all([e != grid[x][j] for x in range(4)])   # column had different color (constraint 2)
                if colonne_valid:
                        #  Find the squares of the same square / constrained 3 /
                        secTopX, secTopY = 1 *(i//1), 1 *(j//1) # use the quotient.
                        for x in range(secTopX, secTopX+1):
                                for y in range(secTopY, secTopY+1):
                                        if grid[x][y] == e:
                                                return False
                        return True
        return False


def sudoku_table(grid, i=0, j=0):
        i,j = Find_blanks(grid, i, j)
        if i == -1:
                return True
        for e in range(1,5):
                if RowColumn_Valid(grid,i,j,e):
                        grid[i][j] = e
                        if sudoku_tableau(grid, i, j):
                                return True
                            
                        grid[i][j] = 0
        return False
    
sudoku = [[1,4,2,0,1],[3,0,0,1,1],[4,0,3,4,2],[0,1,0,0,3]]

sudoku_tableau(sudoku)

print('--------------------Sudoku Coloring-------------')
print(np.matrix(sudoku))

--------------------Sudoku Coloring-------------
[[1 4 2 0 1]
 [3 0 0 1 1]
 [4 0 3 4 2]
 [0 1 0 0 3]]
